version: '3.3'
services:
  goapp:
    ports:
      - "8080:8080"
    image: kaviyakulothungan/goapp:v1
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      KAFKA_HOST: kafka1
      KAFKA_PORT: 9092
      KAFKA_TOPIC: number
      KAFKA_CONSUMER_GROUP: numbers-group
      HTTP_SERVER_PORT: 8080
      HTTP_SERVER_TIMEOUT: 10000